default_config:

ptvsd:
  wait: True # Set to True if you want hass to break and wait for debugger to attach

logger:
  default: info
  logs:
    custom_components.vienna_smartmeter: debug
# If you need to debug uncommment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
debugpy:
