name: Home Assistant

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  hacs:
    runs-on: "ubuntu-latest"
    name: HACS
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v3.2.0"

      - name: HACS validation
        uses: "hacs/action@21.11.0"
        with:
          category: "integration"
          ignore: brands wheels

  hassfest:
    runs-on: "ubuntu-latest"
    name: Hassfest
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v3.2.0"

      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"
